name: tests

on: 
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: tests
    env:
      INSTALL_DEV: true
    runs-on: ubuntu-latest
    container: python:3.10-slim-buster

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: planner_user
          POSTGRES_PASSWORD: planner_password
          POSTGRES_DB: planner_users
        volumes:
          - /src/scripts/init_schema.sh:/docker-entrypoint-initdb.d/init_schema.sh

    steps:
      - uses: actions/checkout@v3

      # - name: Install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install SQLAlchemy
          pip install pydantic
          pip install psycopg2-binary

      - name: Run Tests
        run: |
          pytest authorization && 
          pytest gateway
        working-directory: src/services
